name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install Inkscape
      run: sudo apt-get update && sudo apt-get install -y inkscape zip
    - run: npm ci
    - run: npm run all
    - name: Set up environment for forks
      if: github.ref_name == 'master' && github.event.pull_request.head.repo.full_name != github.repository
      run: |
        echo "GITHUB_ONLY=true" > "$GITHUB_ENV"
        cd dist/
        zip -r ../feather-icons.zip *
    - name: Release
      if: github.ref_name == 'master'
      run: |
        declare -a ARGS
        if [[ $GITHUB_ONLY = true ]]; then
          ARGS+=(--debug --verify-conditions '@semantic-release/github' --publish '@semantic-release/github')
        fi
        npx semantic-release "${ARGS[@]}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
