name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install Inkscape
      run: sudo apt-get update && sudo apt-get install -y inkscape zip
    - run: npm ci
    - run: npm run all
    - name: Set environment variable for forks
      if: github.ref_name == 'master' && github.event.pull_request.head.repo.full_name != github.repository
      run: echo "GITHUB_ONLY='--verify-conditions @semantic-release/github --publish @semantic-release/github'" >> $GITHUB_ENV
    - name: Release
      if: github.ref_name == 'master'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
