name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Inkscape
      run: sudo apt-get update && sudo apt-get install -y inkscape zip
    - run: npm ci
    - run: npm run all
    - name: Archive files
      if: github.ref_name == 'master'
      run: |
        cd dist/
        zip -r ../feather-icons.zip *
    - name: Release
      if: github.ref_name == 'master'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
